[package]
name = "MA-rs"
version = "0.1.0"
edition = "2021"
description = "A Machine Learning framework written and used in Rust"
license = "MIT"
authors = ["Okamitah okamitah@proton.me"]

[dependencies]
